### ISSUE TITLE
Unable to import brightway2 if previously defined user directory is not present

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway2-data#107]
If a previously defined data directory has been removed or renamed, the Python import fails:

```
OSError: BRIGHTWAY2_DIR variable is /home/user/bw_data, but this is not a valid directory
```

More graceful alternatives: 
- [ ] notify the user of the missing directory, ignore the missing directory and use the default directory
- [ ] create the directory (more agressive option)

**Comment by cmutel** [comment]
This is the desired behaviour. We can't guess intent when the user has been clear about what they want, but their configuration is invalid, and I think the error message explains the problem. I adjusted the documentation to make this clearer here: https://github.com/brightway-lca/brightway2/commit/cfaa2a6238a207daec78f256b040a15469d55b50.
