### ISSUE TITLE
Problems with importing numpy

### ISSUE THREAD

**Issue by Joshua-Schroijen** [brightway-lca/brightway2-data#121]
Hello everyone,

When I try to use bw2data's PyPI package without making use of the brightway2 PyPI meta package I tend to get a variety of errors like "ImportError numpy.core.multiarray " when using libraries like matplotlib. I'm using Windows Subsystem for Linux, standard venv Python virtual environments and have tried with Python 3.9 through 3.11. For specific reasons I would like to use the latest and greatest version of bw2data available and I would like not to go with the outdated versions provided by the Brightway2 metapackage.  Does anyone have some advice? Is this a bug that needs fixing?

In case this is a Numpy issue, I opened [an issue at their repository](https://github.com/numpy/numpy/issues/23080). I've followed their own troubleshooting guide to no avail. I've built Numpy from source and made sure my virtual environment was prioritized in my $PATH, but no dice ...

Thanks in advance for your help

**Comment by cmutel** [comment]
@Joshua-Schroijen It seems like this was an issue with a specific VM - can we close this issue?
