### ISSUE TITLE
Pre-Links causes error on windows

### ISSUE THREAD

**Issue by ArashJavan** [brightway-lca/brightway2-data#122]
Hello everyone,
I just installed brightway2 using conda on Windows 11, but unfortunately I get following error during the installation.
The result is, that data is not installed.

```
UserWarning: Package cmutel::bw2data-0.4.1-py_2 uses a pre-link script. Pre-link scripts are potentially dangerous.
This is because pre-link scripts have the ability to change the package contents in the
package cache, and therefore modify the underlying files for already-created conda
environments.  Future versions of conda may deprecate and ignore pre-link scripts.
```

Any idea how to fix this?
Thanks

**Comment by cmutel** [comment]
@ArashJavan Can you please share your installation command? Are you following https://2.docs.brightway.dev/installation.html?

I ask because the version number (`bw2data-0.4.1-py_2`) is very old - we are now on 3.6 for stable and 4 for development.

**Comment by ArashJavan** [comment]
@cmutel thanks for your reply. I finally managed to get brightway running on Windows - after reinstalling my OS.
Now it is working fine so far and the newest packages are installed.
Actually, I am not able to reproduce the error again, but it if it comes up again, I will report the details here.

Thanks for the great work!
