### ISSUE TITLE
add warning when creating an edge of an "unexpected" type

### ISSUE THREAD

**Issue by mfastudillo** [brightway-lca/brightway2-data#132]
when creating a database it is perfectly possible to do something like this

```python
iron_bike.new_edge(amount=12,type='technosphereeee',input=steel).save()
```

I think it would be helpful if it throws a warning, if the type is not one of the expected 'type'. Typos are common when we write strings

**Comment by cmutel** [comment]
https://github.com/brightway-lca/brightway2-data/blob/main/bw2data/backends/typos.py
