### ISSUE TITLE
projects.report() - path problem

### ISSUE THREAD

**Issue by Stew-McD** [brightway-lca/brightway2-data#133]
> bd.projects.report()

gives: *TypeError: unsupported operand type(s) for /: 'str' and 'str'*

this is from line 389:

> sum(os.path.getsize(root / name) for name in files)

it works if I change to:

> sum(os.path.getsize(os.path.join(root, name)) for name in files)

or 

> sum(os.path.getsize(Path(root).joinpath(Path(name))) for name in files)

-----
bw2data.__version__ =  (4, 0, 'DEV18')
OS = Ubuntu 22.10

**Comment by cmutel** [comment]
Thanks Stewart. I am marking this as wont fix, as we will soon be integrating a [completely new projects library](https://github.com/sami-m-g/brightway_projects) and removing this code.
