### ISSUE TITLE
Why no more pure Python wheels of `bw2data` on PyPi?

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway2-data#172]
Hey, @cmutel - it seems you stopped releasing pure Python wheels of this package on PyPi after version `bw2data==4.0.dev32`.

This means I can't install them into a Pyodide distribution.

Is there any specific reason for this change?

**Comment by cmutel** [comment]
Sorry, we switched over to the new packaging template but did some other breaking changes at the same time, so when those breaking changes were reverted we lost the better packaging. But it just so happens that this was fixed two days ago, and the latest release is also available as a wheel.
