### ISSUE TITLE
`parameters.py` Absolute Imports break Sphinx Build

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway2-data#186]
The recent move to absolute imports:

 - https://github.com/brightway-lca/brightway2-data/pull/185

broke the [`inheritance-diagram` functionality of the `autoapi` Sphinx extension](https://sphinx-autoapi.readthedocs.io/en/latest/reference/directives.html#directive-autoapi-inheritance-diagram):

 - https://github.com/readthedocs/sphinx-autoapi/issues/480

A quick workaround would be to simply disable the generation of inheritance diagrams [in `conf.py`](https://github.com/brightway-lca/brightway-documentation/blob/main/source/conf.py) like so:

```python
autoapi_options = [
    'members',
    'undoc-members',
    'private-members',
    'show-inheritance',
    'show-module-summary',
    # 'show-inheritance-diagram' # commented out for debugging
]
```

Passing `-v -v -v` to the `sphinx-build` command, [as documented](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-v) allowed me to narrow the issue down the [`bw2data/parameters.py` file](https://github.com/brightway-lca/brightway2-data/blob/main/bw2data/parameters.py):

```
(...)
[app] emitting event: 'source-read'('api/bw2data/parameters/index', ['bw2data.parameters\n==================\n\n.. py:module:: bw2data.
[app] emitting event: 'build-finished'(SphinxParallelError("AttributeError: 'AssignName' object has no attribute 'getattr'", 'Traceback (m
[AutoAPI] Cleaning generated .rst files

(Error in parallel process)
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sphinx_documentation/lib/python3.12/site-packages/sphinx/util/parallel.py", line 76, in _process
    ret = func(arg)
(...)
```

Manually removing this file will result in a successful Sphinx build.

I will need to leave the remainder of this investigation to the gentlemen who broke the build in the first place (@cmutel et al.) 😬

I created a debugging repository that should make this fairly easy: https://github.com/michaelweinold/sphinx-autoapi-debugging

**Comment by michaelweinold** [comment]
@cmutel, I painstakingly narrowed the issue down to the file/class structure [now replicated here](https://github.com/michaelweinold/sphinx-autoapi-debugging/tree/main/test_library):

`__init__.py`:

```python
from test_library.test_module import banana
```


`test_module.py`:
```python
class highest:
    def __init__(self):
        self.a = 'a'

class middle(highest):
    def __init__(self):
        self.a = 'a'

class lowest:
    def __init__(self):
        self.db = "middle"

test_module = lowest()
```

It is all a little peculiar. If the instance of the `lowest()` class is named something other than the name of the module, such as `banana = lowest()`, no error is thrown. But even if the instance of the `lowest()` class is named `test_module`, the error can be avoided by not making the class `middle()` inherit from another class.

Maybe you can pick this up...

**Comment by cmutel** [comment]
No idea how you even thought to debug in that direction... what about just moving `parameters = ParameterManager()` to `__init__.py`? This shouldn't break too much... the other option would be to change the filename `parameters.py`.

**Comment by michaelweinold** [comment]
> No idea how you even thought to debug in that direction... 

![images](https://github.com/user-attachments/assets/52e24a17-167c-4352-b252-7082af5abde8)

> what about just moving `parameters = ParameterManager()` to `__init__.py`? This shouldn't break too much...

It still does - sorry. You can quickly check my debugging repo: https://github.com/michaelweinold/sphinx-autoapi-debugging

> the other option would be to change the filename `parameters.py`

From what I can see, this should work.

**Comment by michaelweinold** [comment]
I have posted [the MWE from above](https://github.com/brightway-lca/brightway2-data/issues/186#issuecomment-2339227754) in the related issue:

 - https://github.com/readthedocs/sphinx-autoapi/issues/480
