### ISSUE TITLE
LCI instead of unit process data imports of 3.2 causes huge CPU/memory issues

### ISSUE THREAD

**Issue by aleksandra-kim** [brightway-lca/brightway2-data#36]
**[Original report](https://bitbucket.org/cmutel/brightway2-data/issue/36) by Niko Heeren (Bitbucket: [nheeren](https://bitbucket.org/nheeren), GitHub: [nheeren](https://github.com/nheeren)).**

----------------------------------------

When I try to do `data = bw2.Database("ecoinvent 3.2 cutoff").load()` my Mac is busy loading data for ages. I killed the process after it used 40+GB of RAM (!).

Is that the documentation that is contained in ecoinvent 3.2 now? Probably it would be smart to offer a way to load the database without the documentation.

**Comment by aleksandra-kim** [comment]
**Original comment by Chris Mutel (Bitbucket: [cmutel](https://bitbucket.org/cmutel), GitHub: [cmutel](https://github.com/cmutel)).**

----------------------------------------

Resolution is probably to make the correct choice of ecoinvent files much clearer in the documentation.

**Comment by aleksandra-kim** [comment]
**Original comment by Chris Mutel (Bitbucket: [cmutel](https://bitbucket.org/cmutel), GitHub: [cmutel](https://github.com/cmutel)).**

----------------------------------------

See also: http://stackoverflow.com/questions/38383962/saving-multiple-activities-to-database-in-a-loop-in-brightway/38384521#38384521

**Comment by cmutel** [comment]
This is sufficiently explained in documentation for now.
