### ISSUE TITLE
Set output directory with environment variable

### ISSUE THREAD

**Issue by aleksandra-kim** [brightway-lca/brightway2-data#42]
**[Original report](https://bitbucket.org/cmutel/brightway2-data/issue/42) by Chris Mutel (Bitbucket: [cmutel](https://bitbucket.org/cmutel), GitHub: [cmutel](https://github.com/cmutel)).**

----------------------------------------

**Comment by cmutel** [comment]
Existing implementation allows for env vars to set project directory.
