### ISSUE TITLE
Use enum for e.g. type dictionary

### ISSUE THREAD

**Issue by aleksandra-kim** [brightway-lca/brightway2-data#54]
**[Original report](https://bitbucket.org/cmutel/brightway2-data/issue/54) by Chris Mutel (Bitbucket: [cmutel](https://bitbucket.org/cmutel), GitHub: [cmutel](https://github.com/cmutel)).**

----------------------------------------

Either:

* https://pypi.python.org/pypi/enum34
* https://docs.python.org/3/library/enum.html

**Comment by cmutel** [comment]
Brightway 2.5 removes magic mapping values. Strings remain, but making these an enum doesn't add much.
