### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by BenPortner** [brightway-lca/brightway2-data#78]
Tests are failing due to recent changes introduced in the `bw_processing` package. When running 

`python -m pytest ./tests/utils.py
`

I get an error in the line `from bw_processing import load_package` because the function has been renamed. When I change the name, the tests still fail because other components changed as well (e.g. `AttributeError: 'Datapackage' object has no attribute 'keys'
`).

**Comment by cmutel** [comment]
No longer an issue, thankfully.
